language: php
php:
- 5.4
install: npm run build --@neochic/woodlets:version=${TRAVIS_TAG:-latest}
script: npm test
cache:
  directories:
  - node_modules
  - vendor
  - bower_components
deploy:
  provider: releases
  api_key:
    secure: olc+yL9HtSfZVQf6ugp4/ZCvkdzHxkYpwrkmXCd9UASoGPizr288sXYS7yi7zvDBlvOg+NrJkRkt6dYL3d2/oFvJ8KWGPtVeftUwUFRWjAE327uRba+EJoVRXP2ewKapvYW2wPiFxRl4YCK+URqw7u4mVIWFzOTloCMJySl6gtpLyVTzTdvoIXp8oFKved5UbJP5bWiKaH28OfsItF09pwVlurw+K4C8gUkcj+/aa/4CNHzavPRhoTAfzRrnoyaFXB3VRGdLWyLTKx6pAIW7W4hnUbeiexGVkyQ7pHpApRvAyWgcvpf+5pQa2NYkUf7RJa/cfbemgMSlW7n/Z8jt7PyE7Jz0mOX36YPmKRTH4Z+Rke4kklbdBtVHcS9LguZFAiexIKWruUUmPO+v/E+mR8J8Ari8rWMS1t/E5XhDVqTOwjiHcq7C5iNqBrC1xWtr8KwAoPE5JZkDzG6ebuca7d61QQOYmb6Xt2bNhkEmJ8ZBeSccxR3PHiTipeCRAl4hQfNTCe841qJl74i+eQF0iMOoX9CMeLqjz1o1L/1Npc0huxL66UNooG4DR3IS+AiFZuBs5ixxCx+3l3+liEZPdDn8kyvqkX7WMj+1+ivJkBGZ8vR6Ex8v6TTreZwfz6DBd/BfZWC+htQWPdaxOD7jClNnOzxhkVa8PyUlDQQQnZc=
  file_glob: true
  file:
  - woodlets-*.zip
  - woodlets-*.pdf
  skip_cleanup: true
  on:
    repo: Neochic/Woodlets
    tags: true
